baseURL: https://peacewalker122.github.io/
languageCode: en-us
title: peacewalker122
theme: ["PaperMod"]

params:
  homeInfoParams:
    Title: Hi there 👋

  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/peacewalker122"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/danielanugerah"

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod
